default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: marcus_development
  username: marcus_admin
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: marcus_test
  username: marcus_admin
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: marcus_production
  username: marcus_admin
  password: <%= ENV['DB_PASSWORD'] %> # Ensure you set this in your environment variables
  host: <%= ENV['DB_HOST'] || 'localhost' %> # Replace with your Render database host
  port: 5432
  sslmode: require
