default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: marcus_development
  username: marcus_admin
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: marcus_test
  username: marcus_admin
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: marcus_bikes
  username: marcus_bikes_user
  password: <%= ENV['DB_PASSWORD_PROD'] %> # Ensure you set this in your environment variables
  host: <%= ENV['DB_HOST_PROD'] %> # Replace with your Render database host
  port: 5432
  pool: 5
  sslmode: require
